# Generated by Django 5.1.3 on 2024-11-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uf',
            options={'verbose_name': 'UF', 'verbose_name_plural': 'UFs'},
        ),
    ]
